# Generated by Django 5.2.4 on 2025-07-31 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('author_id', models.AutoField(primary_key=True, serialize=False)),
                ('author_name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': '저자',
                'verbose_name_plural': '저자 목록',
                'ordering': ['-author_id'],
            },
        ),
    ]
